name: Test GHA variables

on:
  workflow_dispatch:

jobs:
  test_variables:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check github.event.repository.name variable
        run: echo "The workflow name is ${{ github.event.repository.name }}"
      
      - name: Check github.repository variable
        run: echo "The run ID is ${{ github.repository }}"