name: Fetch input from called workflow

on: 
  workflow_dispatch:

jobs:
  call_input_workflow:
    uses: asmaelkb/AOC2023/.github/workflows/input_wkf.yml@main
    secrets: inherit

  use_output:
    needs: call_input_workflow
    runs-on: ubuntu-latest
    steps:
      - run: echo "The output is ${{ needs.call_input_workflow.outputs.version }}"