# Automatic workflow that builds and deploys demo on DATA
# scheduled to be triggered twice a day
name: CI Data

on:
  schedule:
    - cron: '24 9 * * *'
  workflow_dispatch:
  
jobs:
  call-update-poeditor-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Update POEditor Matrix
        shell: bash
        run: |
          echo "Version : 1"
